### ISSUE TITLE
Be able to view the capital projects ESRI map

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/budget.boston.gov#10]
## User story

People are attracted to maps. This is a map we'd like to display prominently on the Capital Projects tab. People who might not know what a capital project is may stay on this page as a result of seeing the map and choosing to explore.

## Acceptance criteria

1. Website viewers can see [this map](http://app01.cityofboston.gov/BudgetFY17_21/) on the Capital Projects tab landing page. It is not necessary on sub pages.
2. The map is functional on mobile (this may be primarily for the GIS team)
3. Website viewers of the map can zoom in and out on both desktop and mobile

**Comment by jimafisk** [comment]
Added as iframe in intro component.

![capital_projects_map](https://cloud.githubusercontent.com/assets/5913244/23766500/0f9047f8-04d3-11e7-86cd-c036e77156a9.png)

**Comment by hackajesse** [comment]
@jimafisk are you able to determine the level of default zoom in any way? Or is it simply iframe'd in?

**Comment by jimafisk** [comment]
@hackajesse currently it's just iframed in. We might be able to scale it with something like "transform: scale(0.25);"

**Comment by hackajesse** [comment]
This is looking good. Moving to "Done"

**Comment by hackajesse** [comment]
Closing.
