### ISSUE TITLE
Display the Cabinets table (level 2)

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/budget.boston.gov#14]
- [x] The table should be titled "Appropriations by cabinet"
 - [x] The table consists of 5 column headers (L to R): Cabinet, FY15 actual, FY16 actual, FY17 budget, FY18 budget
 - [x] The Cabinet column displays each cabinet in alphabetical order from A to Z
 - [x] On cabinet name click, each cabinet goes to its level 3 table, which is the table displaying the list of departments underneath the selected cabinet
 - [ ] The last row of the Cabinet column should be "Totals:"
 - [x] The data for this table should be from the Operating Budget only. Do not include external funds or capital projects.
 - [ ] To the right of the title of this table, include a hyperlink returning to the Expenditure Categories table. The hyperlink should read "Back to all expenditures"
 - [x] Style per #7

**Comment by jimafisk** [comment]
Title from mockup was "Expenditure Categories" but this has been updated per this issue.

Column header from mockup "Category" was changed to "Cabinet" per this issue.
