### ISSUE TITLE
Display the Capital Projects table (level 1)

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/budget.boston.gov#23]
- [x] The table should be titled "Investment category"
 - [x] The table consists of 7 column headers (L to R): Category, Thru [date], FY17 budget, FY18 budget, FY19-22 budget, Non-capital fund, Total (which is the total amount for each row)
 - [x] The Category column displays each group in alphabetical order from A to Z
 - [x] Category names are clickable and go to the associated level 2 table, which shows departments with projects under that category.
 - [x] The last row of the Category column should be "Totals:"

**Comment by hackajesse** [comment]
Note: need to confirm these column headers with OBM. Meeting on Wednesday 2/8 to confirm.

**Comment by hackajesse** [comment]
Meeting on Wednesday didn't resolve it. Meeting again on Friday 2/10.

**Comment by hackajesse** [comment]
Column headers confirmed by OBM.

**Comment by jimafisk** [comment]
Note that the mockup used the title "Capital Spending through FY22". I've changed it to use the title referenced in this issue.

This table is created manually via the capital-projects.md file. All these items are possible, but need to be configured manually by the user:
- alphabetical ordering
- links to Categories
- totals

Content demonstrates capabilities but needs to be updated to use real numbers and urls

**Comment by hackajesse** [comment]
Need to update the table w/FY18 data
