### ISSUE TITLE
Display Department Capital Projects table (level 2)

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/budget.boston.gov#24]
- [x] The table should be titled "Investments by department"
 - [x] The table consists of 7 column headers (L to R): Department, Thru [date], FY17 forecast, FY18 budget, FY19-22 budget, Non-capital Fund, Total (which is the total amount for each row)
 - [ ] The Department column displays each department with projects in the selected category in alphabetical order from A to Z
 - [x] Department names are clickable and go to the associated level 3 table, which shows all of a selected department's projects.
 - [x] The last row of the Department column should be "Totals:"
 - [x] To the right of the title of this table, include a link returning to the previously selected category table. The hyperlink should read "Back to all categories"
 - [ ] Styled per #7

**Comment by hackajesse** [comment]
Need to confirm column headers with OBM. Doing that at Wednesday 2/8 meeting.

**Comment by hackajesse** [comment]
Meeting on Wednesday didn't resolve it. Meeting again on Friday 2/10.

**Comment by jimafisk** [comment]
For reference, previous title was "Capital by Department through FY22" from mockup -> this has been updated to reflect title from issue

JSON specified table header: "fy-0": "FY17 Budget", -> This has been changed to use the word "Forecast" so Paul will need to update json source.

Alphabetical sorting should be done at JSON source. Jekyll loops through the data in the order it is presented.

Departments names go to the appropriate cp_dept collection.

**Comment by jimafisk** [comment]
Agreed, all styling should come from boston.gov to ensure components stay within guidelines: https://github.com/CityOfBoston/budget.boston.gov/issues/7#issuecomment-283673315

**Comment by jimafisk** [comment]
Moving to review since JSON source and Boston.gov styling are out of the scope of this project. Issues should be open in respective issue queues.

**Comment by hackajesse** [comment]
Moving this back to Ready because of the new JSON templating for FY18.
