### ISSUE TITLE
Every budget tab should have the same sidebar

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/budget.boston.gov#26]
## User story
The sidebar of each of the budget viz tabs should have a consistent set of links to help people understand how the budget works, look up any terms they don't understand, get access to datasets, or get insights into financial management, There will be specific URLs for each within the budget app and having access to the basics of the budget is important. Further, it's important to reduce expected maintenance of any sidebar links as much as possible for City staff.

## Acceptance criteria

1. Admins should be able to update the sidebar and have all sidebars update
2. Sidebars should look the same across all tabs (spacing, font, hyperlinks, icons)
3. Sidebars should have the same mobile responsiveness as Boston.gov sidebar components, not Boston.gov contact information (location on the page, font or icon scaling and wrapping, padding).
4. On mobile, the sidebar slides below all page content (tables, graphs, copy).

**Comment by hackajesse** [comment]
@jimafisk is #4 happening on mobile?

**Comment by jimafisk** [comment]
@hackajesse the side bar slides below the tabs and the intro text. This is the same behavior as seen on Boston.gov. 

Here is a screenshot of the current behavior on the budget app:
![streets-mobile](https://cloud.githubusercontent.com/assets/5913244/24209279/33a157c6-0efc-11e7-9e77-e517a3efbd30.png)

Here is a screenshot of the current behavior on Boston.gov:
![boston-mobile](https://cloud.githubusercontent.com/assets/5913244/24209284/37a629be-0efc-11e7-9b7d-33c4ab959b46.png)

**Comment by hackajesse** [comment]
Confirming this works. Closing.
