### ISSUE TITLE
Department names are not in the correct format in Cabinet level tables

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/budget.boston.gov#260]
If you look at the Administration & Finance cabinet: https://budget.digital-staging.boston.gov/operating-budget/cabinets/administration-and-finance/

You'll see that the department names in the leftmost column are all lower case and there hyphens instead of spaces:

![department_names](https://user-images.githubusercontent.com/5913244/37309061-221939b0-2616-11e8-98c8-0c9b47e778ed.png)

This is how the values are coming across in the JSON source (_source/fy18_adopted/json/_cabinets/administration-and-finance.json) as seen here: https://github.com/CityOfBoston/budget.boston.gov/blob/develop/_source/fy18_adopted/json/_cabinets/administration-and-finance.json#L38

These should look like the values as shown on the live site: https://budget.boston.gov/operating-budget/cabinets/administration-and-finance/

![live_department_values](https://user-images.githubusercontent.com/5913244/37309335-01c411c0-2617-11e8-9d27-3fc1df1fb1cb.png)

**Comment by paulparisi** [comment]
This has been corrected in the JSON files located at \JSON Output\_source\fy18_adopted\json\_cabinets. If it is at other locations please make a note of it.

**Comment by jimafisk** [comment]
This is the location of the Administration & Finance cabinet used in the example: https://github.com/CityOfBoston/budget.boston.gov/blob/develop/_source/fy18_adopted/json/_cabinets/administration-and-finance.json

All the other files in the cabinets folder (`_source/fy18_adopted/json/_cabinets/`) seem to have the same problem in their table components.

**Comment by jimafisk** [comment]
This appears to be fixed with the latest JSON source. Thanks @paulparisi!
