### ISSUE TITLE
Automating Featured Analysis Cards

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/budget.boston.gov#261]
I think there is an opportunity to create more scaffolding for featured analysis cards. Since these are generally similar in structure to each other and are many in number, if we can get these close to "web ready" we can save significant staff time.

The easiest thing to do might be to look at a featured analysis card from fy18_recommended and compare it to the current state of the machine generated cards on fy18_adopted:
- https://budget.boston.gov/featured-analysis/extended-school-day/
- https://budget.digital-staging.boston.gov/featured-analysis/extended-school-day/

When I look at fy18_recommended (the live site), I see that there is a breadcrumb component, an intro component, a sidebar component, then a text block component, and finally a grid component. I also see that there are stylistic things like a callout and multi-column layouts, but I think those can safely be ignored based on earlier conversations. 

![fy18_recommended](https://user-images.githubusercontent.com/5913244/37310114-534841c2-2619-11e8-934e-91e63bc93665.png)

When I look at fy18_adopted (staging site) I only see a text_block component and a grid component.

![fy18_adopted](https://user-images.githubusercontent.com/5913244/37310147-6c468224-2619-11e8-9099-c10a114325ae.png)

The breadcrumbs and the sidebar should be relatively straightforward to add. In fact, if we use the intro component, we'd just need to include a nested key of "sidebar_menu" set to "true" to include the static sidebar menu. The system should also already be aware of the URL patterns, so it just needs to put this into the appropriate component format per the api shown on the [README of this project](https://github.com/CityOfBoston/budget.boston.gov#components).

Then we just need to determine which text should be included as the intro component description. This could be something as simple as the first sentence of the current text_block, or some other rule that we determine makes sense. Even if this sometimes needs to be edited by an analyst later, I think it would save effort to put it in the correct format initially when creating the web copy of this content. The title should already be available in the metadata, again just needs to be put in the appropriate component format.

**Comment by paulparisi** [comment]
If OBM can create guidance on how to abstract the data, we can do this. Would you like me to do something in the meantime?
