### ISSUE TITLE
Broken tables in JSON source

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/budget.boston.gov#264]
The current JSON source for the table on the Operating Budget landing page looks like this:

![broken_table](https://user-images.githubusercontent.com/5913244/37525615-bc68f132-2903-11e8-9820-ad4b5f99f317.png)

This is because the column headings are defined by the first set of JSON keys that it finds in the "columns" value of the table. Ideally these should be broken into separate tables (like "Revenues" and "Expenditures") as seen on the [Operating Budget on the live site](https://budget.boston.gov/operating-budget/). At the very least we'd need to revise the source, which currently looks like this:
```
  "table":[                                              
    {                                                    
      "title":"BUDGET SUMMARY",                          
      "right_text":"Numbers may not add due to rounding",
      "columns":[                            
        {                                                                 
          "Source":"REVENUES",                         
          "value":null
        },        
```
To have a structure that looks more like this:
```
  "table":[                                              
    {                                                    
      "title":"BUDGET SUMMARY",                          
      "right_text":"Numbers may not add due to rounding",
      "columns":[                                        
        {                                                
          "Source":"REVENUES",                           
          "FY15 Actual":null,                            
          "FY16 Actual":null,                            
          "FY17 Budget":null,                            
          "FY18 Budget":null                             
        },                                               
```
That will produce a table that ultimately looks like this:

![adjusted_table](https://user-images.githubusercontent.com/5913244/37526235-355cd774-2905-11e8-8065-6fefb30937f7.png)

**Comment by paulparisi** [comment]
As discussed elsewhere, the tables can be recreated as multiple tables. This will need to be thought through by OBM to see if it matches what they intend. As of now, we will keep it as one table. I have fixed the brokenness so that the "heading" lines have the proper number of null columns.

**Comment by jimafisk** [comment]
This appears to be fixed with the newest JSON source as reflected on the stg site: https://budget.digital-staging.boston.gov/operating-budget/

![table](https://user-images.githubusercontent.com/5913244/37776322-62f2de6c-2dbb-11e8-9438-3cc61a6db1c3.png)

If there are other stylistic tweaks that need to be made to this table, let's open a separate ticket for them.
