### ISSUE TITLE
Incorrect links in Operating Budget landing page table

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/budget.boston.gov#265]
If you look at the Operating Budget landing page on the staging site: https://budget.digital-staging.boston.gov/operating-budget/

The "Budget Summary" table has links that are not 100% correct. Here are some examples:

- Property tax
  - Links to https://budget.digital-staging.boston.gov/featured-analysis/extend-the-school-day
  - Correct page https://budget.digital-staging.boston.gov/featured-analysis/extended-school-day/
- Excises
  - Links to https://budget.digital-staging.boston.gov/featured-analysis/excise-taxes
  - Correct page https://budget.digital-staging.boston.gov/featured-analysis/excise-tax-revenue/
- Fines
  - Links to https://budget.digital-staging.boston.gov/featured-analysis/parking-fines
  - Correct page https://budget.digital-staging.boston.gov/featured-analysis/parking-fine-revenue/

and so on...

Paul and Jim F created these link based on the feature-analysis pages on the live site. However, these pages (and their paths) were created manually for the current live site. It appears that the machine generated paths differ from what was manually created in the past. We should adjust the links in this table to reflect the actual system paths as they exist in the new, machine generated source.

**Comment by paulparisi** [comment]
I have made these changes in my local copy of the "02 Summary Budget - 4 Yr. Budget Summary.xlsx" Excel file. The links need to be verified and Jim F's comments should be reviewed. However, the existing links should work with the next JSON.

**Comment by jimafisk** [comment]
This generally looks very good. Most are fixed, but there are a couple of links still broken:
- https://budget.digital-staging.boston.gov/featured-analysis/extend-the-school-day should be https://budget.digital-staging.boston.gov/featured-analysis/extended-school-day/, however I don't think either of those are the correct link for **Property Tax**. I think this should actually link to https://budget.digital-staging.boston.gov/featured-analysis/property-tax-revenue/
- https://budget.digital-staging.boston.gov/featured-analysis/misc-dept-revenue should be https://budget.digital-staging.boston.gov/featured-analysis/departmental-revenue/

**Comment by paulparisi** [comment]
This can be resolved by OBM in the Excel file that creates these. I can show the appropriate person how to do it.
