### ISSUE TITLE
Dept and Org Names printing lower case with hyphen and org names missing

### ISSUE THREAD

**Issue by jimwilliamson-boston** [CityOfBoston/budget.boston.gov#267]
https://budget.digital-staging.boston.gov/operating-budget/cabinets/administration-and-finance/

Dept lower case with hyphen data not correct
![image](https://user-images.githubusercontent.com/27301004/37536785-fe85010a-2921-11e8-90a2-7b5f7c5617c2.png)

Org names missing and data not correct
![image](https://user-images.githubusercontent.com/27301004/37536859-2b44b1f4-2922-11e8-8350-3f3d5071aa82.png)

**Comment by jimafisk** [comment]
The first half of this issue is related to https://github.com/CityOfBoston/budget.boston.gov/issues/260

**Comment by jimwilliamson-boston** [comment]
OK Thanks

**Comment by paulparisi** [comment]
This is fixed in the JSON now.
