### ISSUE TITLE
Budget Summary Table in Executive Summary - It shouldn't be there

### ISSUE THREAD

**Issue by jimwilliamson-boston** [CityOfBoston/budget.boston.gov#268]
https://budget.digital-staging.boston.gov/

![image](https://user-images.githubusercontent.com/27301004/37539748-f270d26e-292a-11e8-9a8c-f0b2b04c90b9.png)

**Comment by paulparisi** [comment]
This is no longer there. It was there only as an artifact of a demo section. I have removed the section.
