### ISSUE TITLE
No Starting Navigation Table in Capital Projects Tab

### ISSUE THREAD

**Issue by jimwilliamson-boston** [CityOfBoston/budget.boston.gov#269]
https://budget.digital-staging.boston.gov/capital-projects/

**Comment by paulparisi** [comment]
Is there a table that is similar to this in the printed documents? If so please point me to the page number in the PDF so I can make that output as JSON. If not, I will have to create the table and will need to know how the numbers are compiled. I could guess but it would be better to have specifics.

**Comment by jimwilliamson-boston** [comment]
Adding Jack Hanlon.  Short answer. No, there is not array of this data in
the printed version of the document, but underlying data can be extracted
from capital publishing tables in BudgetSoft Editor 2-3.

**Comment by jimwilliamson-boston** [comment]
Duplicate with item 252

**Comment by jimafisk** [comment]
Just linking to https://github.com/CityOfBoston/budget.boston.gov/issues/252
