### ISSUE TITLE
JSON Not Rendering?

### ISSUE THREAD

**Issue by paulparisi** [CityOfBoston/budget.boston.gov#278]
[phc-administration.json.txt](https://github.com/CityOfBoston/budget.boston.gov/files/1857574/phc-administration.json.txt)

Take a look at this JSON file which is located at 

\JSON Output\_source\fy19_recommended\json\_programs\health-and-human-services\public-health-commission

The page you suggested does not match the JSON above.

https://budget.digital-staging.boston.gov/operating-budget/cabinets/health-and-human-services/public-health-commission/phc-administration/

**Comment by jimafisk** [comment]
Here's the corresponding JSON source on GitHub: https://github.com/CityOfBoston/budget.boston.gov/blob/develop/_source/fy18_recommended/json/_programs/health-and-human-services/public-health-commission/administration.json

- [Name](https://github.com/CityOfBoston/budget.boston.gov/blob/develop/_source/fy18_recommended/json/_programs/health-and-human-services/public-health-commission/administration.json#L9) = the Title of the page
- [Description](https://github.com/CityOfBoston/budget.boston.gov/blob/develop/_source/fy18_recommended/json/_programs/health-and-human-services/public-health-commission/administration.json#L18) = A truncated version of what is appearing in the intro under the title. There must be a filter in the template that does this truncation. We should at least try to truncate on a word boundary if we think that's important to have.
- [Head Name](https://github.com/CityOfBoston/budget.boston.gov/blob/develop/_source/fy18_recommended/json/_programs/health-and-human-services/public-health-commission/administration.json#L7), [Head Title](https://github.com/CityOfBoston/budget.boston.gov/blob/develop/_source/fy18_recommended/json/_programs/health-and-human-services/public-health-commission/administration.json#L8), and [Appropriation Code](https://github.com/CityOfBoston/budget.boston.gov/blob/develop/_source/fy18_recommended/json/_programs/health-and-human-services/public-health-commission/administration.json#L17) are appearing below the intro sentence in bold.
- [Program History By Account](https://github.com/CityOfBoston/budget.boston.gov/blob/develop/_source/fy18_recommended/json/_programs/health-and-human-services/public-health-commission/administration.json#L56) = The info in the table on the page

Is the main issue that not all the information from the JSON file is making it to the page? The way we produced for fy18_recommended was the JSON source had tons of information in it that we never used. We pulled out the critical aspects into a template and ignored the rest. @paulparisi are there specific areas that displayed previously, but no longer do?

**Comment by paulparisi** [comment]
Ah - there is quite a bit of code running to produce the JSON. I was not aware that large parts were not rendered. I understood that certain keys would be ignored but not that large sections. 

So, is there a way to tell me what is not being rendered? 

This will allow me to greatly simplify the output. Right now, for example, the bureaus is a complicated set of data the OBM does not even have sources for. So my output routine broke and I did not know why I could not see it in the HTML.

**Comment by jimafisk** [comment]
Ok that makes sense. I don't definitively know enough about what should or should not be rendered on the site. I can tell you what we did last year. Here's the same page on the live site: https://budget.boston.gov/operating-budget/cabinets/health-and-human-services/public-health-commission/administration/

I'd defer to @jimwilliamson-boston as to whether or not bureaus should be rendering. Thanks!

**Comment by jimwilliamson-boston** [comment]
We do not capture PHC bureau-level data in Hyperion so it is not part of
the data used in BudgetSoft 2-3.

**Comment by paulparisi** [comment]
I have removed the PHC bureau functions from the code. We should be able to close this.
