### ISSUE TITLE
Pages seem delayed

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/budget.boston.gov#31]
When on the tabbed content pages, they seem to have a delay when scrolling and on mouseover. 

Please investigate and lmk!

**Comment by jimafisk** [comment]
This seems to be a chrome only bug. Still not exactly sure where this style is being applied but it may be something similar to this screenshot:
![slow_scrolling_culprit](https://cloud.githubusercontent.com/assets/5913244/23766290/278c1b62-04d2-11e7-94ea-baf47f224a87.png)
